# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [10]:
# Your code goes here
import pandas as pd
import numpy as np
df1=pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv')
df2=pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv')
df3=pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv')
df1.columns
df2.columns
df1.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [13]:
df1.shape

(4008, 11)

In [14]:
df2.shape

(996, 11)

In [15]:
df3.shape

(996, 11)

In [18]:
# To combine 3 dataframes into one , when they have same columns and 
#different no of row values.Use ignore_index to reset the index
df_combined = pd.concat([df1, df2,df3], ignore_index=True)

In [19]:
df_combined.shape

(6000, 11)

In [20]:
#cleaning the dataframe after maintaing a copy for backup
df=df_combined.copy()

In [22]:
#clean 
df.columns=df.columns.str.lower()
df.columns=df.columns.str.strip()
df.columns=df.columns.str.replace(' ','_')
df.rename(columns={'st':'state'},inplace=True)
df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [23]:
# Your code here
female_keywords=["Femal","female","fema"]
male_keywords=["Male","male"]
df['gender']=df['gender'].apply(lambda value :"F" if value in female_keywords else value)
df['gender']=df['gender'].apply(lambda value :"M" if value in male_keywords else value)

In [24]:
df['gender'].unique()

array([nan, 'F', 'M'], dtype=object)

In [25]:
abbrevation={
    'AZ':'Arizona',
    'Cali':'California',
    'WA':'Washington'
}
df['state']=df['state'].apply(lambda x: abbrevation[x] if x in abbrevation else x)
df['state'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan],
      dtype=object)

In [26]:
#replace the "Bachelors" value in education column to "Bachelor"
df.replace({'education':'Bachelors'},'Bachelor', inplace=True)
df['education'].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [27]:
df['customer_lifetime_value']=df['customer_lifetime_value'].str.replace('%','',regex=False)
df['customer_lifetime_value'].unique()

array([nan, '697953.59', '1288743.17', ..., '568964.41', '368672.38',
       '399258.39'], dtype=object)

In [28]:
keywords=["Sports Car", "Luxury SUV" , "Luxury Car"]
df['vehicle_class']=df['vehicle_class'].apply(lambda value :"Luxury" if value in keywords else value)
df['vehicle_class'].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

In [29]:
print(df.dtypes)

customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value       object
income                       float64
monthly_premium_auto         float64
number_of_open_complaints     object
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object


In [31]:
df['customer_lifetime_value'] = pd.to_numeric(df['customer_lifetime_value'], errors='coerce'
                                            )
df['number_of_open_complaints']=df['number_of_open_complaints'].apply(lambda x: int(x.split("/")[1]) 
                                                                     if isinstance(x, str) and '/' in x else np.nan)
df['number_of_open_complaints']=pd.to_numeric(df['number_of_open_complaints'], errors='coerce')

In [32]:
df['number_of_open_complaints'].unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [33]:
df['customer_lifetime_value'].unique()

array([       nan,  697953.59, 1288743.17, ...,  568964.41,  368672.38,
        399258.39])

In [34]:
df['customer'].isnull().sum()


np.int64(2937)

In [35]:
df.dropna(subset=["customer"], inplace=True)

In [36]:
df['customer'].isnull().sum()

np.int64(0)

In [37]:
df.fillna({'customer_lifetime_value':df['customer_lifetime_value'].mean()},inplace=True )
df['customer_lifetime_value'].mean()

np.float64(775136.8260091743)

In [38]:
df['customer_lifetime_value'].isnull().sum()

np.int64(0)

In [44]:
#To replace gender using mode <mode return series so index [0] , for F
df.fillna({'gender':df['gender'].mode()[0]},inplace=True )
df['gender'].mode()

0    F
Name: gender, dtype: object

In [46]:
df['gender'].isnull().sum()

np.int64(0)

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [48]:
# Your code goes here
df_new=pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv')

In [49]:
df_new.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

In [60]:
df_new.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
10905    False
10906    False
10907    False
10908    False
10909    False
Length: 10910, dtype: bool

In [63]:
df_new['sales_channel'].unique()

array(['Agent', 'Call Center', 'Branch', 'Web'], dtype=object)

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [67]:
summary_table = df_new.pivot_table(values='total_claim_amount', index='sales_channel', aggfunc='sum')
summary_table.style.format({"total_claim_amount": "{:,.2f}"})
display(summary_table)
#df['total_claim_amount'] = df['total_claim_amount'].apply(lambda x: f"{x:,.2f}")

total_claim_amount
sales_channel                    
Agent                1.810227e+06
Branch               1.301204e+06
Call Center          9.266008e+05
Web                  7.066000e+05

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [71]:
table=df_new .pivot_table(
    values='customer_lifetime_value', 
    index='gender', 
    columns='education', 
    aggfunc='mean')
display(table)

education     Bachelor      College       Doctor  High School or Below  \
gender                                                                   
F          7874.269478  7748.823325  7328.508916           8675.220201   
M          7703.601675  8052.459288  7415.333638           8149.687783   

education       Master  
gender                  
F          8157.053154  
M          8168.832659

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [73]:
# Your code goes here
summary_tab=df.groupby(['month', 'policy_type'])['number_of_open_complaints'].sum().reset_index()
display(summary_tab)

month     policy_type  number_of_open_complaints
0      1  Corporate Auto                 443.434952
1      1   Personal Auto                1727.605722
2      1    Special Auto                  87.074049
3      2  Corporate Auto                 385.208135
4      2   Personal Auto                1453.684441
5      2    Special Auto                  95.226817